### ISSUE TITLE
Rate limiting

### ISSUE THREAD

**Issue by taylorfinnell** [DataDog/dogapi-rb#111]
Does this gem provide an api to retrieve current rate limits. From what I could see in the code, the response does nothing with the http headers.

http://docs.datadoghq.com/api/?lang=ruby#ratelimiting

**Comment by degemer** [comment]
Indeed @taylorfinnell, `dogapi` does nothing with the rate-limit headers.  Do you have something particular in mind ? (https://github.com/piotrmurach/github#142-response-headers for instance ?)

**Comment by taylorfinnell** [comment]
Something like how Github's works would be great. But, it looks like the current response format is `[http_code, json_response]`. I think making it work like Github's, ie: `response.headers.ratelimit_limit` would require a change to what kind of object is returned as the response, I think such a change would be a breaking change. What do you think?

**Comment by degemer** [comment]
Definitely a breaking change, it would probably be the best solution though.

I think the easiest way to get the rate limits without breaking anything would be to add it to `handle_response` - https://github.com/DataDog/dogapi-rb/blob/fd48f5048a880e8dd2ce3dbc67b7612ecc6cc2c2/lib/dogapi/common.rb#L144-L154, and store it for every endpoint.
It couldn't be part of the response, so we would have to add a method to retrieve it.
I'm open to suggestions !

**Comment by taylorfinnell** [comment]
I wouldn't mind doing it the way Github does it (response.headers.ratelimit, etc) for the next major version of the gem. If you would like I can start making the change to introduce some new Response object instead of the currently returned array. Since it is a breaking change I suppose the PR can just hang around until the next major version.

**Comment by degemer** [comment]
Thank you for the proposition @taylorfinnell !
Definitely a good improvement for 2.0. I have a few other improvements in mind, but this would be a very good start.
I'll be happy to review any PR about starting to implement this change.

**Comment by dgreene-r7** [comment]
Hi. We'd love to see some movement on this ticket as well. Do you have any initial work done on 2.0 that we could contribute to?

**Comment by gzussa** [comment]
Leaving this as closed since no PR were provided and since last comment was made in 2017. Also, introducing backward incompatible changes is something we try to avoid at this point with this library. We will work on a new library fixing a lot of issue seen in this library. However, I cannot provide any ETA at the moment.
