### ISSUE TITLE
No capistrano deploy notifications seen on event stream dashboard

### ISSUE THREAD

**Issue by IanVaughan** [DataDog/dogapi-rb#122]
Viewing all (or just capistrano) event stream (https://app.datadoghq.com/event/stream), I never see any capistrano events.

I have at the very top of my `Capfile`
```
require "capistrano/datadog"
set :datadog_api_key, 'retracted'
```

And have the following gem versions
* dogapi (1.25.0)
* capistrano (3.4.0)

Debuging within [`lib/capistrano/datadog.rb`][1], I can get a real cap event, and also create a test_event from your specs.

The real event does not show up, but the test one does.

[1]:https://github.com/DataDog/dogapi-rb/blob/8e00014a538d1f67273a7c5a264c42a4397517ab/lib/capistrano/datadog.rb#L30

```
# a real cap event
[17] pry(Capistrano::Datadog)> event = reporter.report.first
[18] pry(Capistrano::Datadog)> event
=> [#<Dogapi::Event:0x007ff8aacded30
  @aggregation_key="0cda32bb5db83f5e3a4b2eb31feb2f84",
  @alert_type="success",
  @date_happened=1489151435,
  @event_type="deploy",
  @msg_text="",
  @msg_title="ian@ian.local ran staging on  with capistrano in 1.07 secs",
  @parent=nil,
  @priority="normal",
  @source_type_name="capistrano",
  @tags=["#capistrano"]>,
 []]

# send it (cannot see it on event stream)
[19] pry(Capistrano::Datadog)> dog.emit_event event.first
=> ["202",
 {"status"=>"ok",
  "event"=>
   {"id"=>973689024792381642,
    "title"=>"ian@ian.local ran staging on  with capistrano in 1.07 secs",
    "text"=>"",
    "date_happened"=>1489151435,
    "handle"=>nil,
    "priority"=>"normal",
    "related_event_id"=>nil,
    "tags"=>["#capistrano"],
    "url"=>"https://app.datadoghq.com/event/event?id=973689024792381642"}}]

# test event
[23] pry(Capistrano::Datadog)> test_event
=> #<Dogapi::Event:0x007ff8aac90770
 @aggregation_key="job-123",
 @alert_type="error",
 @date_happened=1489151540,
 @event_type=nil,
 @msg_text="Uh-oh, something bad happened",
 @msg_title="Alert! Alert!",
 @parent=nil,
 @priority="normal",
 @source_type_name=nil,
 @tags=["ruby", "dogapi"]>

# send it (it shows up on the event stream)
[24] pry(Capistrano::Datadog)> dog.emit_event test_event
=> ["202",
 {"status"=>"ok",
  "event"=>
   {"id"=>973689153003286310,
    "title"=>"Alert! Alert!",
    "text"=>"Uh-oh, something bad happened",
    "date_happened"=>1489151540,
    "handle"=>nil,
    "priority"=>"normal",
    "related_event_id"=>nil,
    "tags"=>["ruby", "dogapi"],
    "url"=>"https://app.datadoghq.com/event/event?id=973689153003286310"}}]

```

**Comment by kwwalter** [comment]
Discussing this issue with @IanVaughan on ticket number 84588

**Comment by IanVaughan** [comment]
Thanks, as per discussion on ticket, it is all working fine, just that Capistrano deploy events are "low PRIORITY", set this filter and they all show up, nice!

@kwwalter also linked to this nice gif that explains it without words https://cl.ly/1z2l1c1L2j1P

I'd vote to update the docs about this!

All working fine, closing.

**Comment by kmshultz** [comment]
@IanVaughan I'll update our docs, as you suggested! Mind if we use that Gif? I don't see any sensitive information in it, but since it's your account, I understand if you'd rather we not use it.

**Comment by kwwalter** [comment]
Glad to hear that solved the issue for you, @IanVaughan! Feel free to drop us a line at support@datadoghq.com if anything else comes up.
