### ISSUE TITLE
Missing endpoints in Ruby Client

### ISSUE THREAD

**Issue by l0k0ms** [DataDog/dogapi-rb#137]
The following endpoints don't have a dedicated method in the Datadog Ruby client:

* [Cancel monitor downtimes by scope](https://docs.datadoghq.com/api/?lang=ruby#cancel-monitor-downtimes-by-scope)
* [Get monitor downtime](https://docs.datadoghq.com/api/?lang=ruby#get-a-monitor-downtime)
* [Integrations](https://docs.datadoghq.com/api/?lang=ruby#integrations)
* [Get list of active metrics](https://docs.datadoghq.com/api/?lang=ruby#get-list-of-active-metrics)
* [Resolve monitor](https://docs.datadoghq.com/api/?lang=ruby#resolve-monitor)
* [Organizations](https://docs.datadoghq.com/api/?lang=ruby#organizations)
* [Usage](https://docs.datadoghq.com/api/?lang=ruby#usage-metering)

**Comment by davidcpell** [comment]
Same question, specifically about integrations. Is this work planned by any chance?

**Comment by gzussa** [comment]
I am closing this issue which is a feature request. It is also too wide to be tracked properly. As per our new contributing guide, we are asking the community to open support tickets for feature requests.  Of course, we are also welcoming pull requests 😃

**Comment by gzussa** [comment]
Also, some of these endpoints are already implemented. I invite the community to double check based on their needs. Feel free to contact our support for missing endpoints that you may need.
