### ISSUE TITLE
v1.29.0 is tagged inconsistently with the rest of the project

### ISSUE THREAD

**Issue by mcwqy9** [DataDog/dogapi-rb#150]
v1.29.0 is tagged `1.29.0` and should be tagged `v1.29.0` to be consistent with the rest of the project. 

I noticed this because I was surprised to find commits for v1.29.0 when the lexicographically descending list of tags in the github UI implies that v1.28.0 is latest.

**Comment by masci** [comment]
Fixed, thanks
