### ISSUE TITLE
Metric type support is out of date

### ISSUE THREAD

**Issue by seth-outreach** [DataDog/dogapi-rb#154]
Per https://docs.datadoghq.com/api/?lang=ruby#post-time-series-points valid metric types are `gauge`, `rate`, and `count`, however the validation (https://github.com/DataDog/dogapi-rb/blob/master/lib/dogapi/v1/metric.rb#L64) only allows `gauge` and the deprecated `counter`.

**Comment by asafpelegcodes** [comment]
Any update on this issue?

**Comment by zippolyte** [comment]
Closing, this was fixed with #165
