### ISSUE TITLE
Return values of high-level operations are fairly loosely structured lists. Best way to determine success or failure?

### ISSUE THREAD

**Issue by alq666** [DataDog/dogapi-rb#18]
Since ruby does not provide elegant pattern matching or guards, this means doing things like:

``` ruby
x = dog.emit_event(...)
# success or failure?
x[0].to_i / 100 == 2
# event data url
x[1]['event']['url']
```

Brittle.

Is there a ruby-friendly way to prevent this kind of logic from bleeding outside of the module?

**Comment by gzussa** [comment]
This issue is old and doesn't seem to be getting traction. Leaving it closed
