### ISSUE TITLE
Emitting event using Dogapi in Chef 12 returns with an empty event

### ISSUE THREAD

**Issue by WToorenburghEasyMarkit** [DataDog/dogapi-rb#202]
Hey there,

I have a custom Chef cookbook that deploys our application code to our machines, running in OpsWorks Stacks. I'm trying to get the cookbook to report to Datadog when a deployment has finished, with supporting information, so I'm using the Dogapi gem to do this. I pass along the event like so:

```ruby
if node.run_state[:datadog_enabled]
  datadog_databag = search('aws_opsworks_app', 'shortname:datadog').first
  chef_gem 'dogapi'
  require 'dogapi'

  datadog_agent = Dogapi::Client.new(datadog_databag[:environment][:api_key])
end

revision = File.readlink("#{node[:nginx][:web_content_directory]}/#{app[:shortname]}/current").split('/').last
# Transforming a string like git@bitbucket.org:<org>/admin.git to an HTTPS url
url = app[:app_source][:url]
      .sub(':', '/') # Fixing the colon after bitbucket.org
      .sub('git@', 'https://') # Swapping out for the correct protocol
      .sub('.git', "/commits/#{revision}") # Completing the link to the commit

resp = datadog_agent.emit_event(
  Dogapi::Event.new(
    msg_title: "App #{app[:shortname].capitalize} deployed to #{node[:hostname].capitalize}.#{node[:deployment][:zone_id].capitalize}",
    msg_text: "Deployed revision [#{revision}](#{url})",
    alert_type: 'success',
    aggregation_key: revision,
    host: "#{node[:hostname].capitalize}.#{node[:deployment][:zone_id].capitalize}",
    tags: [
      "zone_id:#{node[:deployment][:zone_id]}",
      "service:#{app[:shortname]}"
    ],
    source_type_name: 'chef'
  )
)
```

The request succeeds, but does not have any of the information I supposedly sent along:

```json
[
  "202",
  {
    "status": "ok",
    "event": {
      "id": 5199653833307866819,
      "title": "",
      "text": nil,
      "date_happened": 1574186385,
      "handle": nil,
      "priority": "normal",
      "related_event_id": nil,
      "tags": [],
      "url": "https://app.datadoghq.com/event/event?id=5199653833307866819"
    }
  }
]
```

The event in Datadog is also empty. The tags that get attached are seemingly random as well. Sometimes there are no tags at all, sometimes there are all the tags dd-handler would have attached, sometimes a varying amount in between. Am I doing something wrong here, or is there a bug I'm running into?

**Comment by jeremy-lq** [comment]
@WToorenburghEasyMarkit We'll need some additional information to help troubleshoot. Please open a [support ticket](
https://docs.datadoghq.com/help/) and will pick things up from there.

**Comment by justi** [comment]
msg_text should be defined as the first parameter in Dogapi::Event constructor.
