### ISSUE TITLE
Please release new version of gem

### ISSUE THREAD

**Issue by toddself** [DataDog/dogapi-rb#228]
**Describe the bug**
Service Level Objective API is implemented in the gem, but not available from ruby gems

Label the issue properly.
- Add `severity/` label.
- Add `documentation` label if this issue is related to documentation changes.

**To Reproduce**
1. bundle install 1.39.0
2. try to use `search_service_leveLobjective`
3. See error

**Expected behavior**
The service level objective APIs should be availab;e

**Environment and Versions (please complete the following information):**
Ruby 2.6.5, dogapi gem 1.39.0

**Comment by zippolyte** [comment]
New version of the gem is released, which includes the SLO change: https://rubygems.org/gems/dogapi/versions/1.40.0
