### ISSUE TITLE
Capistrano integration does not allow to specify api host 

### ISSUE THREAD

**Issue by ktimothy** [DataDog/dogapi-rb#230]
As I figured out from code, I can set host by specifying `ENV['DATADOG_HOST']`, but explicit configuration would be much better:

```ruby 
set :datadog_api_key, '*** key ***'
set :datadog_api_host, 'https://api.datadoghq.eu/api/'
```

I can provide a PR, if you are be interested in this.

**Comment by gzussa** [comment]
Thanks for suggesting your help. That would be much appreciated 😄.  cc @DataDog/agent-platform

**Comment by macobo** [comment]
This is still an issue
