### ISSUE TITLE
sending events with Ruby API assigns host tags, even if host isn't specified

### ISSUE THREAD

**Issue by celenechang** [DataDog/dogapi-rb#42]
In contrast, Python API will only append a host's tags if that host is specified in the post.

**Comment by zippolyte** [comment]
Won't change the default behavior so as not to break anything for current users.
If you don't want to have a host tag associated, simply specify `host: ""` or even `host: nil` when sending the event:
```ruby
dog.emit_event(Dogapi::Event.new("message"), host: nil)
```
