### ISSUE TITLE
hostname -s option produces error on some Windows versions

### ISSUE THREAD

**Issue by celenechang** [DataDog/dogapi-rb#57]
when Dogapi::Client.new() is invoked, it runs `hostname -s`

causes an error on, for example:
Windows 7 Professional SP 1,
Windows Server 2008 R2 Standard SP1

desk case: 18595

**Comment by violetaria** [comment]
Also happens on Windows 8.1

**Comment by petterl** [comment]
On Windows 10 I get:

    sethostname: Use the Network Control Panel Applet to set hostname.
    hostname -s is not supported.

**Comment by gzussa** [comment]
@celenechang is this still valid?
