### ISSUE TITLE
dogapi hungs?

### ISSUE THREAD

**Issue by takus** [DataDog/dogapi-rb#66]
I sends some metrics via fluent-plugin-dd, and sometimes its thread hungs. According to stacktrace, It seems that dogapi hungs in connecting https session. Any ideas to fix it?

https://gist.github.com/takus/26a73772c21ce2c6df98

**Comment by yannmh** [comment]
Hi @takus,

Thanks for reporting this issue. 
By default, `dogapi-rb` has a 5 seconds timeout: beyond, the connection attempt should be dropped. I suspect that the issue could be related with `fluent-plugin-dd` as it possibly overrides this `timeout` [value](https://github.com/winebarrel/fluent-plugin-dd#configuration).

Would you be able to provide us more information on your `dogapi-rb` settings through this plugin ?

Thanks

**Comment by takus** [comment]
Hi @yannmh,

Thanks for replying. I checked both source code, and default timeout of each lib is `nil`. I think the setting causes this issue. It seems that `Dogapi::APIService` has a 5 seconds timeout, but `Dogapi::Client`. Is that correct?

https://github.com/winebarrel/fluent-plugin-dd/blob/c141905d3ce203f8a6ef3a7800e2a5a559a499c1/lib/fluent/plugin/out_dd.rb#L13

https://github.com/DataDog/dogapi-rb/blob/a4d3e1c4995bf3187347bd67a4ac8f6c483c8d60/lib/dogapi/facade.rb#L14

Thanks

**Comment by takus** [comment]
The previous comment is wrong. Dogapi::Client uses `Dogapi::v1::xxx` in internal. But I noticed that #55 seems to be related to this issue. I'll try to upgrade to the latest version at first.

**Comment by yannmh** [comment]
Great. 
Please let me know if upgrading solved your issue.

**Comment by takus** [comment]
@yannmh 
It seems that upgrading solved the issue.
Thanks.
