### ISSUE TITLE
execution expired message

### ISSUE THREAD

**Issue by jeremymv2** [DataDog/dogapi-rb#71]
I'm getting these messages every once in a while and when it happens the metrics don't show up in Datadog.

Emitting data to Datadog..
execution expired

code:
<pre>
require 'dogapi'

def emit_to_datadog(failed,pipeline_name,pipeline_url,deploy_dict,elapsed_seconds)
  puts "\n\n\tEmitting data to Datadog.."
  api_key = ENV['DD_API_KEY'] || 'xxxxx'
  begin
    dog = Dogapi::Client.new(api_key)

    result = failed ? 'Failed' : 'Success'

    dog.emit_event(Dogapi::Event.new("Result: #{result}\n#{pipeline_url}\nItems Deployed: #{deploy_dict}",
      :msg_title       => "Deployment - Pipeline: #{pipeline_name}",
      :aggregation_key => "#{pipeline_url}",
      :alert_type      => failed ? 'error' : 'success',
      :tags            => ["#{pipeline_name}"]
    ))

    dog.emit_point('deployment.duration', elapsed_seconds, :type => 'gauge')
    dog.emit_point('deployment.success', 1, :type => 'counter') if !failed
    dog.emit_point('deployment.failed', 1, :type => 'counter') if failed

  rescue Exception => e
    puts "\n\n\tGot an Error attempting to send data to DataDog: #{e}"
  rescue Timeout::Error => te
    puts "\n\n\tRescued from timeout: #{te}"
  end
end
</pre>
The exception handling above is not catching the error.  Any ideas? 

The data being sent is fairly important so I'd like to at least be able to catch timeout type errors and re-try an emit.

**Comment by yannmh** [comment]
Hey @jeremymv2  ,
Sorry to hear that you're experiencing trouble with the dogapi-rb.
Would you have the full exception trace to help us understanding what's happening ?

**Comment by yannmh** [comment]
@jeremymv2 are you still experiencing any issue ?

**Comment by yannmh** [comment]
Closing, please feel free to re-open if needed.
