### ISSUE TITLE
getting connection refused

### ISSUE THREAD

**Issue by ikenney** [DataDog/dogapi-rb#77]
I have a rails project that I am trying to set up to push metrics to datadog using the dogapi-rb gem
I am getting a connection refused error when I try to send data - for example from the rails console:

    > dog = Dogapi::Client.new( "my-api-key" )
    #<Dogapi::Client ....
    > dog.emit_point('test.api.test_metric',4.0)
    Connection refused - connect(2) for nil port 80
    => [-1, {}]

**Comment by remh** [comment]
@ikenney are you behind a proxy maybe ? it looks like a misconfiguration somewhere. The connection to datadog is using HTTPS, so it's using port 443.

**Comment by yannmh** [comment]
@ikenney we haven't heard back from you.

I am closing the issue, but please feel free to reopen with more information.
