### ISSUE TITLE
Test mode?

### ISSUE THREAD

**Issue by bobbytables** [DataDog/dogapi-rb#80]
Hi, I was wondering if there are plans to introduce a testing mode for clients?

**Comment by yannmh** [comment]
Apologies for the late answer @bobbytables. 

I am not sure to understand your question :grimacing:. Could you define what you are calling "testing mode for clients" please ?  


Yann

**Comment by bobbytables** [comment]
No sweat! So I think I opened this on the wrong repo looking back. I was talking about `dogstatsd-ruby` and introducing a test mode there. I'll open something there.
