### ISSUE TITLE
Query metrics is missing?

### ISSUE THREAD

**Issue by gtmtech** [DataDog/dogapi-rb#86]
Can you currently query metrics?

I couldn't find it in this API, unlike the Python version, or shell APIDocs.

Or have I gone mad... thanks

**Comment by yannmh** [comment]
Hi @gtmtech,

You're not mad, this feature is not implemented in `dogapi-rb` yet. We can work on extending the support to it. Would this feature help you and your team ?

Yann

**Comment by rceee** [comment]
@yannmh This would definitely help me and my team.  We are able to post metrics easily using dogstatsd-ruby.  But we need a way to query metrics.  Can this feature be extended?

**Comment by blakehilscher** [comment]
Hi I need this feature. I am going to implement it. Are you accepting pull requests?

**Comment by yannmh** [comment]
Sorry for the late answer @rceee, @blakehilscher. 

I am adding the request to our `1.22.0` milestone: it'll be addressed in the upcoming release which should be out in ~10 days. 

@blakehilscher, we'll be happy to review your pull request if you decide to make one :smiley:

**Comment by yannmh** [comment]
Fixed with #88 and #90.
