### ISSUE TITLE
DogAPI reports vague error: Cannot determine local hostname via hostname -f

### ISSUE THREAD

**Issue by tschellhorn** [DataDog/dogapi-rb#87]
It happens that on a node that is short on memory, the chef run was failing to converge and reporting an error:

```
Cannot determine local hostname via hostname -f
```

The problem happens at https://github.com/DataDog/dogapi-rb/blob/master/lib/dogapi/common.rb#L163 where it doesn't report the exception that is thrown. The actual issues was due to the following error:

```
Cannot allocate memory - hostname
```

**Comment by yannmh** [comment]
Hi @tschellhorn,

Sorry to hear that you are experiencing issues with `dogapi-rb` and thanks for the detailed feedback.

I think we can do a better job, here, at handling hostname resolution exceptions: we could simply log a warning message with the exception message, and fallback with no hostname.
On a side note, a short term workaround could be to manually set up a `hostname` during the `initialize` call, to avoid any hostname resolution c.f. https://github.com/DataDog/dogapi-rb/blob/master/lib/dogapi/facade.rb#L26. 

Please let me know what you think about it. We'll consider the appropriate changes for the upcoming release.

Yann

**Comment by tschellhorn** [comment]
I came across the error on one of our nodes running Chef with the Datadog cookbook. I tracked the problem down to the Dogapi. I looked at the code for how the dd-handler is included in in the Chef cookbook recipe and there is no hostname that is passed over so I don't think I would be able to set the hostname explicitly in the DogAPI object. (https://github.com/DataDog/chef-handler-datadog/blob/master/lib/chef/handler/datadog.rb#L22)

Fixing this for the next milestone is okay with me. I just wanted to point out the minor issue to help other users in the future.

**Comment by degemer** [comment]
https://github.com/DataDog/chef-datadog/pull/308 should fix this issue if you set a hostname in Chef. (released in chef-datadog 2.5.0) 
As @yannmh said, it would be nice to have a better hostname resolution, we'll see what we can do.

**Comment by degemer** [comment]
We could raise a more explicit error `DatadogHostnameError` for instance. We'll see if we can change it for 2.0, since it doesn't seem to be a blocker.

**Comment by cabrinha** [comment]
I'm seeing this behavior a lot in my logs: ```2019-08-01T23:42:27.343Z ERROR [qtp2021405400-4879] [puppetserver] Puppet Report processor failed: Cannot determine local hostname via hostname -f```

**Comment by cabrinha** [comment]
bump.

**Comment by gzussa** [comment]
@cabrinha What we are discussing here may help in your context. https://github.com/DataDog/dogapi-rb/pull/179. 

@degemer @yannmh did the chef fix fixed the issue? I am not sure to understand from this thread if we can pass along the hostname now or not. What this issue open to better handle exceptions?

**Comment by cabrinha** [comment]
> @cabrinha What we are discussing here may help in your context. #179.
> 
> @degemer @yannmh did the chef fix fixed the issue? I am not sure to understand from this thread if we can pass along the hostname now or not. What this issue open to better handle exceptions?

Thanks for the reply, but the `hostname` binary is available in my case.

It does return the short name, however. Could that be the issue I'm having? Is DogAPI RB expecting the FQDN, including the TLD? 

If so, we should allow users to set that themselves.

**Comment by gzussa** [comment]
Reopening this so @yannmh and @degemer can provide some guidance. cc @dabcoder as well
