### ISSUE TITLE
Capistrano doctor raises exception on Logger

### ISSUE THREAD

**Issue by nielsm** [DataDog/dogapi-rb#94]
If you have require 'capistrano/datadog' in your capfile and then run cap production doctor, you get an error NoMethodError: undefined method `write' for #<Logger:0x007ff793b0a940>.  /usr/local/var/rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/dogapi-1.22.0/lib/capistrano/datadog/v3.rb:33:in `write'
/usr/local/var/rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/sshkit-1.10.0/lib/sshkit/formatters/pretty.rb:53:in `write_message'
/usr/local/var/rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/sshkit-1.10.0/lib/sshkit/formatters/pretty.rb:12:in `write'

**Comment by rmoriz** [comment]
Looks like this issue came up with the recent capistrano 3.5.0 release

**Comment by degemer** [comment]
Thanks for reporting @nielsm & @rmoriz. This PR should fix the issue: https://github.com/DataDog/dogapi-rb/pull/96

**Comment by degemer** [comment]
https://github.com/DataDog/dogapi-rb/pull/96 is merged and will be released with 1.23.0.
